// AUTO-GENERATED by upload-emojis.mjs (repo root) — do not edit by hand.
// Run `DISCORD_TOKEN=xxx DISCORD_APPLICATION_ID=xxx node upload-emojis.mjs`
// after adding/renaming icons in that script's EMOJI_SOURCES list, then
// commit the regenerated version of this file.
//
// Empty until that script has been run at least once — emoji.ts falls back
// to "" for any key not present here, so nothing breaks in the meantime.
export const EMOJI_MAP: Record<string, string> = {};
