// Looks up a Discord application-emoji tag (e.g. "<:coin:123456789012345>")
// for a given icon key. Embeds can only show ONE image/thumbnail each, so
// for anywhere multiple items need their own visual in the same embed
// (upgrade panel, pet list, crate panel, ...) we prefix the item's name
// with its emoji instead.
//
// The map is generated by running upload-emojis.mjs (repo root) — see that
// file for how to run it. Until it's been run, emoji() returns "" for
// everything and emojiPrefix() returns "", so nothing breaks — items just
// show without a leading emoji, same as before.
import { EMOJI_MAP } from "./emoji-map";

export function emoji(key: string): string {
  return EMOJI_MAP[key] ?? "";
}

// Convenience: the emoji tag + a trailing space, or "" if that key hasn't
// been uploaded yet — use this directly in front of an item's name.
export function emojiPrefix(key: string): string {
  const e = emoji(key);
  return e ? `${e} ` : "";
}
