// AUTO-GENERATED by upload-emojis.mjs — do not edit by hand.
// Run `DISCORD_TOKEN=xxx DISCORD_APPLICATION_ID=xxx node upload-emojis.mjs`
// again after adding/renaming icons in that script's EMOJI_SOURCES list.
export const EMOJI_MAP: Record<string, string> = {
  "factory_icon": "<:factory_icon:1552782061310574675>",
  "miner_icon": "<:miner_icon:1552782067182469130>",
  "ore_copper_3": "<:ore_copper_3:1552782072081285212>",
  "ore_silver_3": "<:ore_silver_3:1552782077047349350>",
  "ore_gold_3": "<:ore_gold_3:1552782082244349995>",
  "ore_platinum_3": "<:ore_platinum_3:1552782087898005647>",
  "ore_emerald_3": "<:ore_emerald_3:1552782094160363640>",
  "ore_diamond_3": "<:ore_diamond_3:1552782099575083079>",
  "pet_mole": "<:pet_mole:1552782104675483680>",
  "pet_bat": "<:pet_bat:1552782110421549096>",
  "pet_owl": "<:pet_owl:1552782115509375091>",
  "pet_slime": "<:pet_slime:1552782121083469834>",
  "pet_golem": "<:pet_golem:1552782126716293282>",
  "pet_crystalfox": "<:pet_crystalfox:1552782132760547328>",
  "coin": "<:coin:1552782137843916806>",
  "gem": "<:gem:1552782143980044309>",
  "shard": "<:shard:1552782149101289603>",
  "pet_shard": "<:pet_shard:1552782155279503460>",
  "prestige_token": "<:prestige_token:1552782161130557461>",
  "crate_common": "<:crate_common:1552782166591541278>",
  "crate_rare": "<:crate_rare:1552782172874866708>",
  "crate_epic": "<:crate_epic:1552782178901950504>",
  "crate_legendary": "<:crate_legendary:1552782185151463487>",
  "booster_global": "<:booster_global:1552782190667108472>",
  "booster_gm": "<:booster_gm:1552782196832600064>",
  "corp_icon": "<:corp_icon:1552782202369081356>",
  "rebirth_icon": "<:rebirth_icon:1552782208266272881>"
};
