/*
  upload-emojis.mjs
  Uploads a curated set of this bot's icon PNGs as Discord *application
  emojis* — owned by the bot application itself (not any one server), so
  they work in every server the bot is in and don't eat into any server's
  own emoji slots. Writes the resulting name -> "<:name:id>" mapping to
  src/game/emoji-map.ts.

  Run once, and again any time you add/rename an entry in EMOJI_SOURCES
  below (already-uploaded names are skipped, so it's safe to re-run):
    DISCORD_TOKEN=xxx DISCORD_APPLICATION_ID=xxx node upload-emojis.mjs

  After it finishes: commit the regenerated src/game/emoji-map.ts and
  redeploy (git push) — no schema change, no register.mjs run needed.
*/
import { readFileSync, writeFileSync, existsSync } from "node:fs";

const token = process.env.DISCORD_TOKEN;
const appId = process.env.DISCORD_APPLICATION_ID;

if (!token || !appId) {
  console.error("Set DISCORD_TOKEN and DISCORD_APPLICATION_ID environment variables first.");
  process.exit(1);
}

// Emoji names must be 2-32 chars, alphanumeric + underscores — every icon
// filename below already satisfies that. Add more icon keys here any time
// (they must exist as assets/icons/<key>.png).
const EMOJI_SOURCES = [
  // upgrades
  "factory_icon", "miner_icon", "exp_icon",
  // ores — one emoji per type, using the mid-tier "form 3" art
  "ore_copper_3", "ore_silver_3", "ore_gold_3", "ore_platinum_3", "ore_emerald_3", "ore_diamond_3",
  // pets
  "pet_mole", "pet_bat", "pet_owl", "pet_slime", "pet_golem", "pet_crystalfox",
  // currencies
  "coin", "gem", "shard", "pet_shard", "prestige_token",
  // stat badges added for the profile/corp emoji pass
  "materials_icon", "income_icon", "prestige_icon", "corp_buff_icon",
  // crates
  "crate_common", "crate_rare", "crate_epic", "crate_legendary",
  // boosters / misc
  "booster_global", "booster_gm", "corp_icon", "rebirth_icon",
];

const mapFilePath = new URL("./src/game/emoji-map.ts", import.meta.url);

function readExistingMap() {
  if (!existsSync(mapFilePath)) return {};
  const text = readFileSync(mapFilePath, "utf8");
  const match = text.match(/EMOJI_MAP:\s*Record<string,\s*string>\s*=\s*(\{[\s\S]*?\});/);
  if (!match) return {};
  try {
    // The generated object literal is plain JSON-compatible (string keys/values).
    return JSON.parse(match[1]);
  } catch {
    return {};
  }
}

async function listAppEmojis() {
  const res = await fetch(`https://discord.com/api/v10/applications/${appId}/emojis`, {
    headers: { Authorization: `Bot ${token}` },
  });
  const json = await res.json();
  if (!res.ok) {
    console.error("Failed to list existing application emojis:", json);
    process.exit(1);
  }
  return json.items ?? [];
}

async function uploadEmoji(name, base64Png) {
  const res = await fetch(`https://discord.com/api/v10/applications/${appId}/emojis`, {
    method: "POST",
    headers: { Authorization: `Bot ${token}`, "content-type": "application/json" },
    body: JSON.stringify({ name, image: `data:image/png;base64,${base64Png}` }),
  });
  const json = await res.json();
  if (!res.ok) {
    console.error(`Failed to upload "${name}":`, json);
    return null;
  }
  return json;
}

async function deleteEmoji(id) {
  const res = await fetch(`https://discord.com/api/v10/applications/${appId}/emojis/${id}`, {
    method: "DELETE",
    headers: { Authorization: `Bot ${token}` },
  });
  if (!res.ok && res.status !== 404) {
    console.error(`Failed to delete emoji id ${id}:`, await res.json());
    return false;
  }
  return true;
}

const existing = await listAppEmojis();
const existingByName = new Map(existing.map((e) => [e.name, e]));
const result = readExistingMap();

// Discord's app-emoji API can only rename an existing emoji, not replace its
// image — so if the art changed, the old one is deleted first and a fresh
// one created with the same name. This means every run re-uploads every
// icon in EMOJI_SOURCES (not just new ones), which is slower but keeps the
// emoji in sync any time you update assets/icons/*.png and re-run this.
for (const name of EMOJI_SOURCES) {
  const filePath = new URL(`./assets/icons/${name}.png`, import.meta.url);
  if (!existsSync(filePath)) {
    console.warn(`Skipping ${name} — assets/icons/${name}.png not found`);
    continue;
  }

  if (existingByName.has(name)) {
    const ok = await deleteEmoji(existingByName.get(name).id);
    if (!ok) { console.warn(`Couldn't delete old "${name}" — leaving it as-is.`); continue; }
    await new Promise((r) => setTimeout(r, 500));
  }

  const base64 = readFileSync(filePath).toString("base64");
  const created = await uploadEmoji(name, base64);
  if (created) {
    result[name] = `<:${created.name}:${created.id}>`;
    console.log(`Uploaded: ${name} -> ${result[name]}`);
  }
  // Discord rate-limits emoji creation fairly aggressively — small delay
  // between uploads to avoid 429s.
  await new Promise((r) => setTimeout(r, 800));
}

const fileText =
  `// AUTO-GENERATED by upload-emojis.mjs — do not edit by hand.\n` +
  `// Run \`DISCORD_TOKEN=xxx DISCORD_APPLICATION_ID=xxx node upload-emojis.mjs\`\n` +
  `// again after adding/renaming icons in that script's EMOJI_SOURCES list.\n` +
  `export const EMOJI_MAP: Record<string, string> = ${JSON.stringify(result, null, 2)};\n`;

writeFileSync(mapFilePath, fileText);
console.log(`\nWrote ${Object.keys(result).length} emoji mappings to src/game/emoji-map.ts`);
console.log("Commit this file and git push so the bot can use them (no schema/register.mjs step needed).");
